# Publish To NPM
name: publish-npm

# Publish on push to [master]
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner on which this job will run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.16.3']

    # Steps represent a sequence of tasks that will be executed as part of the job
    # - Checkout project
    # - Run `npm install` to get dependencies
    # - TODO: Run npm tests prior to release
    # - Run `npm release` which takes care of the rest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build and Release
        run: npm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}          
